### ISSUE TITLE
Java version required for minced?

### ISSUE THREAD

**Issue by milw** [tseemann/prokka#162]
hi, I just installed Prokka on Ubuntu 14, but get an error with minced - looks like my java version is not appropriate? Is there an update for minced.jar, or should I pursue installing the required java version?
<[10:49:55] Looking for 'minced' - found /home/scott/prokka/bin/../binaries/linux/../common/minced
Exception in thread "main" java.lang.UnsupportedClassVersionError: minced : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[10:49:55] Could not determine version of minced - please install version 1.6 or higher

$ java -showversion
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)>

**Comment by milw** [comment]
OK, found the minced master on github, recompiled on my system and replaced the minced.jar that had been supplied with the prokka distribution.
https://github.com/ctSkennerton/minced

**Comment by nafizh** [comment]
Can you write in a detailed manner how you solved the problem? I am getting the same errors.

**Comment by tseemann** [comment]
Their minced was compiled with Java 1.8, see https://github.com/ctSkennerton/minced/issues/12

You can get a Java 1.6 jar here: https://github.com/ctSkennerton/minced/releases/tag/0.2.0

I will put that one into Prokka.
